function(target_link_system_library target scope lib)
    get_target_property(lib_include_dirs ${lib} INTERFACE_INCLUDE_DIRECTORIES)
    target_include_directories(${target} SYSTEM ${scope} ${lib_include_dirs})
    target_link_libraries(${target} ${scope} ${lib})
endfunction()

function(target_link_system_libraries target)
    set(options)
    set(singleValueArgs)
    set(multiValueArgs INTERFACE PUBLIC PRIVATE)
    cmake_parse_arguments(ARG "${options}" "${singleValueArgs}" "${multiValueArgs}" ${ARGN})
    foreach(scope IN ITEMS INTERFACE PUBLIC PRIVATE)
        foreach(lib IN LISTS ARG_${scope})
            target_link_system_library(${target} ${scope} ${lib})
        endforeach()
    endforeach()
endfunction()
